### ISSUE TITLE
(void-function magit--checkout)

### ISSUE THREAD

**Issue by dabrahams** [magit/magit-imerge#15]
(1) what behavior you expected

aborting an imerge works

    (2) what behavior you observed

See title

    (3) and how we can reproduce the issue.

With magit checked out at f55be50f, abort a magit-imerge

```
Debugger entered--Lisp error: (void-function magit--checkout)
  magit--checkout("stdlib-serialization")
  #<subr magit-imerge-abort>()
  apply(#<subr magit-imerge-abort> nil)
  #f(compiled-function (fn &rest args) #<bytecode 0x3006706562954d7>)(#<subr magit-imerge-abort>)
  apply(#f(compiled-function (fn &rest args) #<bytecode 0x3006706562954d7>) #<subr magit-imerge-abort> nil)
  (lambda (fn &rest args) (interactive #f(compiled-function (spec) #<bytecode -0x9e249f3b72d570d>)) (apply '#f(compiled-function (fn &rest args) #<bytecode 0x3006706562954d7>) fn args))(#<subr magit-imerge-abort>)
  apply((lambda (fn &rest args) (interactive #f(compiled-function (spec) #<bytecode -0x9e249f3b72d570d>)) (apply '#f(compiled-function (fn &rest args) #<bytecode 0x3006706562954d7>) fn args)) #<subr magit-imerge-abort> nil)
  magit-imerge-abort()
  funcall-interactively(magit-imerge-abort)
  command-execute(magit-imerge-abort)
```

Also post the output of:

    M-x magit-version RET

Magit v3.3.0-567-gf55be50f, Git 2.39.3, Emacs 29.1, darwin

**Comment by kyleam** [comment]
This repo's c63ab1a (2023-05-21) switched to using `magit--checkout` to adjust for Magit's 2ddb7ca45 (Mark async branch and checkout commands for interactive use only, 2023-05-21).  You're on a Magit commit before that f55be50f1 (2023-03-14).

Upgrading Magit would resolve the issue.  If you're stuck on that revision of Magit for some reason, then downgrading Magit-imerge to v1.2.0 (or any version before c63ab1a) would likely give you a compatible version.

---

I don't think this is documented anywhere and it should be, but the general approach with the Magit extensions under the Magit organization is to stay in lockstep with the tip of Magit's `main`, without adding kludges to stay compatible with the latest release of Magit (or older releases).  So, you can expect the last release of an extension to be compatible with the last release of Magit, and the tip of the extension's development branch to be compatible with Magit's `main`. 

This topic was discussed a bit previously at magit/magit-annex#27.

**Comment by dabrahams** [comment]
If releases are marked by tags, it looks like they are really, really rare and I might be best off trying to keep up with main if I want things to work with a recent emacs?

**Comment by kyleam** [comment]
> [...] I might be best off trying to keep up with main if I want things to work with a recent emacs?

I think that's generally true, though in this case the `magit--checkout` change is really the only code change since 1.2.0.  I'm not aware of 1.2.0 having any incompatibilities with recent Emacs versions.

There's nothing more planned for Magit-imerge feature-wise, so at this point changes to master are likely to be 1) adjusting for changes in Magit , 2) adjusting in backward-compatible way with changes in Emacs, and 3) bug fixes.

The next Magit-imerge release will happen shortly after Magit is released.

**Comment by kyleam** [comment]
I said:
> I don't think this is documented anywhere and it should be [...]

I've made a note to do that.
