### ISSUE TITLE
Feature request: (instructions for) integration into `magit-dispatch`

### ISSUE THREAD

**Issue by dabrahams** [magit/magit-imerge#16]
It's lovely that you give instructions for rebinding `magit-mode-map` keys, and I'm really happy to rebind `i`, which I've used by mistake too often.  But sometimes I forget what the binding is so I hit `?` and it's confusing not to see “`i imerge`” in the resulting menu.  It would be great to have integration into that menu, or instructions for producing that integration.

Thanks for your wonderful module.

**Comment by kyleam** [comment]
Thanks for the suggestion, and sorry for the delayed response.

> or instructions for producing that integration

Added a snippet to the commentary.
